---
- name: Restart TigerVNC
  ansible.builtin.service:
    name: "vncserver@{{ item.display }}.service"
    state: restarted
  loop: "{{ tigervnc_users }}"
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - item.service_enabled | default(tigervnc_default_service_enabled) | bool
  become: true
